<?php

$runbook = 'docs/operations/R6-sli-slo-alert-policy.md';

return [
    'threshold_policy' => 'provisional_operational_signal',

    'slo_bindings' => [
        'failed_jobs' => ['is_definitive_slo' => false, 'status' => 'decision_pending'],
        'queue_backlog' => ['is_definitive_slo' => false, 'status' => 'decision_pending'],
        'dlq_count' => ['is_definitive_slo' => false, 'status' => 'decision_pending'],
        'dlq_oldest_age_seconds' => ['is_definitive_slo' => false, 'status' => 'decision_pending'],
        'scheduler_freshness_seconds' => ['is_definitive_slo' => false, 'status' => 'decision_pending'],
    ],

    'catalog' => [
        'api_5xx_increase' => [
            'name' => 'API 5xx increase',
            'sli' => 'api_availability',
            'signal' => 'HTTP 5xx responses divided by total API responses',
            'condition' => '5xx ratio above documented provisional range for the window',
            'severity' => 'SEV2',
            'window' => '5m and 30m',
            'owner' => 'engineering_on_call',
            'first_action' => 'Check readiness, recent deploy/runtime errors, database and cache health',
            'runbook' => $runbook,
            'close_condition' => '5xx ratio returns below provisional range for two consecutive windows',
            'external_integration' => false,
        ],
        'api_latency_degraded' => [
            'name' => 'API latency degraded',
            'sli' => 'api_latency',
            'signal' => 'p95 API latency from application performance logs',
            'condition' => 'p95 above documented provisional range for the window',
            'severity' => 'SEV3',
            'window' => '15m',
            'owner' => 'engineering_on_call',
            'first_action' => 'Identify slow endpoints and check database/cache saturation',
            'runbook' => $runbook,
            'close_condition' => 'p95 returns below provisional range for two consecutive windows',
            'external_integration' => false,
        ],
        'charge_creation_failure' => [
            'name' => 'Charge creation failure',
            'sli' => 'charge_creation_success',
            'signal' => 'Failed charge creation attempts divided by total charge creation attempts',
            'condition' => 'Failure ratio above documented provisional range',
            'severity' => 'SEV2',
            'window' => '15m',
            'owner' => 'payments_engineering',
            'first_action' => 'Check validation errors, idempotency errors, gateway adapter state, and no orphan charge invariant',
            'runbook' => $runbook,
            'close_condition' => 'Charge creation success returns to provisional range',
            'external_integration' => false,
        ],
        'webhook_processing_failure' => [
            'name' => 'Webhook processing failure',
            'sli' => 'webhook_processing_success',
            'signal' => 'Failed webhook processing events divided by accepted webhook events',
            'condition' => 'Failure ratio above documented provisional range or DLQ receives new pending items',
            'severity' => 'SEV2',
            'window' => '15m',
            'owner' => 'payments_engineering',
            'first_action' => 'Check webhook logs by correlation id and verify DLQ growth without exposing payload',
            'runbook' => $runbook,
            'close_condition' => 'Webhook failures stop and DLQ growth stabilizes',
            'external_integration' => false,
        ],
        'queue_backlog_high' => [
            'name' => 'Queue backlog high',
            'sli' => 'queue_backlog',
            'signal' => 'Read-only queue backlog count from deep health',
            'condition' => 'Deep health queue_backlog returns WARN or ERROR',
            'severity' => 'SEV3',
            'window' => 'current and 15m trend',
            'owner' => 'platform_engineering',
            'first_action' => 'Check worker availability, queue backend health, and job throughput',
            'runbook' => $runbook,
            'close_condition' => 'Backlog returns below provisional WARN threshold and trend is decreasing',
            'external_integration' => false,
        ],
        'failed_jobs_high' => [
            'name' => 'Failed jobs high',
            'sli' => 'failed_jobs',
            'signal' => 'failed_jobs count from deep health',
            'condition' => 'Deep health failed_jobs returns WARN or ERROR',
            'severity' => 'SEV2',
            'window' => 'current and 15m trend',
            'owner' => 'platform_engineering',
            'first_action' => 'Inspect sanitized failure classes and correlate with worker logs',
            'runbook' => $runbook,
            'close_condition' => 'Failed jobs count returns below provisional WARN threshold after documented handling',
            'external_integration' => false,
        ],
        'dlq_growth' => [
            'name' => 'DLQ growing',
            'sli' => 'dlq_pending',
            'signal' => 'Pending DLQ count and oldest pending age from deep health',
            'condition' => 'DLQ count or oldest age returns WARN/ERROR or count increases over consecutive windows',
            'severity' => 'SEV2',
            'window' => '15m',
            'owner' => 'payments_engineering',
            'first_action' => 'Triage DLQ metadata only; avoid exposing payload, tenant data, headers, or signatures',
            'runbook' => $runbook,
            'close_condition' => 'DLQ growth stops and pending count/age return below provisional WARN range',
            'external_integration' => false,
        ],
        'scheduler_delayed' => [
            'name' => 'Scheduler delayed',
            'sli' => 'scheduler_freshness',
            'signal' => 'Scheduler heartbeat age from deep health',
            'condition' => 'scheduler_freshness returns WARN or ERROR',
            'severity' => 'SEV3',
            'window' => 'current and 10m trend',
            'owner' => 'platform_engineering',
            'first_action' => 'Check scheduler process, cache store, and one-server lock health',
            'runbook' => $runbook,
            'close_condition' => 'Heartbeat returns OK for two consecutive checks',
            'external_integration' => false,
        ],
        'gateway_degraded' => [
            'name' => 'Gateway degraded',
            'sli' => 'gateway_success',
            'signal' => 'Gateway adapter failures, timeouts, and circuit breaker state',
            'condition' => 'Gateway failures above provisional range or circuit breaker open',
            'severity' => 'SEV2',
            'window' => '15m',
            'owner' => 'payments_engineering',
            'first_action' => 'Check gateway logs, circuit breaker state, and inbound webhook acceptance',
            'runbook' => $runbook,
            'close_condition' => 'Gateway success returns to provisional range and circuit closes',
            'external_integration' => false,
        ],
        'settlement_inconsistent' => [
            'name' => 'Settlement inconsistent',
            'sli' => 'settlement_consistency',
            'signal' => 'Settlement reconciliation anomalies and wallet reserve mismatches',
            'condition' => 'Any critical reconciliation inconsistency detected',
            'severity' => 'SEV1',
            'window' => 'per reconciliation run',
            'owner' => 'finance_operations',
            'first_action' => 'Pause unsafe settlement actions and run reconciliation triage',
            'runbook' => $runbook,
            'close_condition' => 'Reconciliation is clean or discrepancy has approved documented resolution',
            'external_integration' => false,
        ],
        'database_unavailable' => [
            'name' => 'Database unavailable',
            'sli' => 'dependency_database_availability',
            'signal' => 'Readiness database check and deep health dependency reads',
            'condition' => 'Database check returns ERROR/DOWN',
            'severity' => 'SEV1',
            'window' => 'current',
            'owner' => 'platform_engineering',
            'first_action' => 'Confirm database connectivity and protect financial write paths',
            'runbook' => $runbook,
            'close_condition' => 'Database readiness returns OK and dependent checks recover',
            'external_integration' => false,
        ],
        'redis_unavailable' => [
            'name' => 'Redis unavailable',
            'sli' => 'dependency_redis_availability',
            'signal' => 'Readiness Redis check, queue Redis read, and scheduler heartbeat cache read',
            'condition' => 'Redis/cache check returns ERROR or scheduler heartbeat cannot be read',
            'severity' => 'SEV2',
            'window' => 'current and 5m',
            'owner' => 'platform_engineering',
            'first_action' => 'Check Redis/cache connectivity and queue/scheduler impact',
            'runbook' => $runbook,
            'close_condition' => 'Redis readiness and dependent checks return OK',
            'external_integration' => false,
        ],
        'api_key_abuse' => [
            'name' => 'API key abuse suspected',
            'sli' => 'api_key_abuse_rate',
            'signal' => 'Authentication failures, scope denials, and rate limiter events per credential fingerprint',
            'condition' => 'Abuse indicators exceed provisional range without exposing raw credential values',
            'severity' => 'SEV3',
            'window' => '15m',
            'owner' => 'security_operations',
            'first_action' => 'Review sanitized security logs and rate-limit or revoke per policy when confirmed',
            'runbook' => $runbook,
            'close_condition' => 'Abuse indicators return to normal and suspicious credentials are handled',
            'external_integration' => false,
        ],
        'backup_restore_failure_future' => [
            'name' => 'Backup or restore verification failure future policy',
            'sli' => 'backup_restore_verification',
            'signal' => 'Future backup verification and restore dry-run results',
            'condition' => 'Future backup/restore verification fails when DR scope is implemented',
            'severity' => 'SEV2',
            'window' => 'per future DR verification run',
            'owner' => 'platform_engineering',
            'first_action' => 'Future policy only in R6.6; do not integrate backup/restore alerting yet',
            'runbook' => $runbook,
            'close_condition' => 'Future verification succeeds or documented remediation is approved',
            'external_integration' => false,
        ],
    ],
];
