<?php

return [
    'general_settings' => [
        'title' => 'Configurações Gerais',
        'icon'  => 'cil-equalizer',

        'elements' => [
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'logo',
                'label' => 'Logotipo',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:1000',
                'value' => 'img/logo.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'light_logo',
                'label' => 'Logotipo Claro',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:1000',
                'value' => 'img/logo.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'small_logo',
                'label' => 'Logotipo Pequeno',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:1000',
                'value' => 'img/logo.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'site_favicon',
                'label' => 'Favicon do Site',
                'rules' => 'mimes:jpeg,jpg,png,ico,,svg|max:1000',
                'value' => 'img/favicon.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'login_banner',
                'label' => 'Banner de Login',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:2000',
                'value' => 'img/welcome-vector.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'default_breadcrumb_image',
                'label' => 'Imagem Padrão do Cabeçalho',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:2000',
                'value' => 'img/welcome-vector.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'site_title',
                'label' => 'Título do Site',
                'rules' => 'required|min:2|max:500',
                'value' => 'Coevs',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'hidden',
                'data'  => 'bool',
                'key'   => 'site_preloader',
                'rules' => 'required|boolean',
                'value' => 0,
            ],
            [
                'type'          => 'group_text',
                'data'          => 'string',
                'key'           => 'preloader_text',
                'label'         => 'Pré-carregador do Site',
                'related_field' => 'site_preloader',
                'rules'         => 'required',
                'value'         => 'Loading',
                'class'         => 'col-md-6',
                'message'       => 'Insira o texto para ser exibido no pré-carregador, separado por vírgulas.',            ],
            [
                'type'    => 'text',
                'data'    => 'string',
                'key'     => 'admin_prefix',
                'label'   => 'Prefixo do Admin',
                'rules'   => 'required|max:10',
                'value'   => 'admin',
                'class'   => 'col-md-6',
                'message' => 'Prefixo das rotas do painel admin. Ao alterar, você precisará fazer login novamente com o novo prefixo para ter efeito.',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'site_timezone',
                'label' => 'Fuso Horário do Site',
                'rules' => 'required',
                'value' => [],
                'class' => 'col-md-6',
            ],
            [
                'type'    => 'select',
                'data'    => 'string',
                'key'     => 'home_redirect',
                'label'   => 'Redirecionamento da Página Inicial',
                'rules'   => 'required',
                'value'   => [],
                'class'   => 'col-md-6',
                'message' => 'Slugs de Todas as Páginas',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'support_email',
                'label' => 'Email de Suporte',
                'rules' => 'required|min:4|max:199',
                'value' => 'support@demo.com',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'support_phone',
                'label' => 'Telefone de Suporte',
                'rules' => 'required|min:4|max:199',
                'value' => '+1234567890',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'copyright_text',
                'label' => 'Texto de Direitos Autorais',
                'rules' => 'required|min:4|max:199',
                'value' => 'admin',
                'class' => 'col-md-12',
            ],

        ],
    ],
    'site_security' => [
        'title'    => 'Configurações de Segurança',
        'icon'     => 'security',
        'elements' => [
            [
                'type'  => 'switch',
                'data'  => 'bool',
                'key'   => 'force_https',
                'label' => 'Forçar HTTPS',
                'rules' => 'required|boolean',
                'value' => 0,
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'hidden',
                'data'  => 'bool',
                'key'   => 'screen_lock',
                'rules' => 'required|boolean',
                'value' => 0,
            ],
            [
                'type'          => 'group_text',
                'data'          => 'integer',
                'key'           => 'screen_lock_time',
                'label'         => 'Bloqueio de Tela',
                'unit'          => 'minutos',
                'related_field' => 'screen_lock',
                'rules'         => 'required|integer',
                'value'         => 5,
                'class'         => 'col-md-5',
            ],
            [
                'type'  => 'group_text',
                'data'  => 'integer',
                'key'   => 'submission_lock_duration',
                'label' => 'Trava contra Envios Duplicados',
                'unit'  => 'segundos',
                'info'  => 'Valor recomendado: 5',
                'rules' => 'required|integer',
                'value' => 5,
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'group_text',
                'data'  => 'integer',
                'key'   => 'max_upload_size',
                'label' => 'Tamanho Máximo de Upload',
                'unit'  => 'MB',
                'rules' => 'required|integer|min:1',
                'value' => 5,
                'class' => 'col-md-4',
            ],
        ],
    ],

    'efi_settings' => [
        'title'    => 'Configurações Efí (Gerencianet)',
        'icon'     => 'wallet',
        'elements' => [
            [
                'type'  => 'switch',
                'data'  => 'bool',
                'key'   => 'efi_auto_withdraw',
                'label' => 'Saque Automático (PIX Envios)',
                'rules' => 'required|boolean',
                'value' => 0,
                'class' => 'col-md-6',
                'info'  => 'Se ativado, os saques serão processados imediatamente de forma automática. Se desativado, os saques ficarão pendentes aguardando aprovação manual do administrador.',
            ],
        ],
    ],

    'maintenance_mode' => [
        'title'     => 'Configurações de Manutenção',
        'info'      => 'Atenção: Ao ativar o Modo de Manutenção você precisa lembrar da Chave Secreta para conseguir desativá-lo.',
        'info_icon' => 'fa fa-exclamation-triangle text-warning',
        'icon'      => 'cil-memory',
        'elements'  => [
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'maintenance_cover',
                'label' => 'Imagem de Capa',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:2000',
                'value' => '',
                'class' => 'col-md-12',
            ],
            [
                'type'    => 'text',
                'data'    => 'string',
                'key'     => 'secret_key',
                'label'   => 'Chave Secreta',
                'rules'   => 'required',
                'value'   => 'secret',
                'class'   => 'col-md-12',
                'message' => 'Lembre-se da chave: dominio.com/chave-secreta. Use-a para conseguir acessar o site durante a manutenção.',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'maintenance_title',
                'label' => 'Título',
                'rules' => 'required',
                'value' => 'Site is not under maintenance',
                'class' => 'col-md-12',
            ],
            [
                'type'  => 'textarea',
                'data'  => 'string',
                'key'   => 'maintenance_text',
                'label' => 'Texto de Manutenção',
                'rules' => 'required|max:500',
                'value' => 'Sorry for interrupt! Site will live soon.',
                'class' => 'col-md-12',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'site_environment',
                'label' => 'Ambiente do Site',
                'rules' => 'required',
                'value' => [],
                'class' => 'col-md-12',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'development_mode',
                'label'   => 'Modo de Desenvolvimento (Depuração)',
                'rules'   => 'boolean',
                'value'   => true,
                'class'   => 'col-md-6',
                'message' => 'Ative este recurso apenas quando precisar depurar erros ou alterar códigos.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'maintenance_mode',
                'label'   => 'Modo de Manutenção',
                'rules'   => 'boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'Ligue apenas se quiser bloquear o acesso público ao site.',
            ],
        ],
    ],
    'mail_settings' => [
        'title' => 'Configurações de E-mail SMTP',
        'info'  => 'Ao usar SMTP do Gmail, seu "Endereço de Remetente" pode ser substituído. Para enviar e-mails com um endereço personalizado (como suporte@seudominio.com), use um provedor SMTP verificado como Mailgun, Amazon SES ou o servidor do seu domínio com SPF e DKIM configurados. O teste enviará um e-mail para confirmar as configurações.',
        'icon'             => 'cil-send',
        'include_partials' => '_smtp_test',
        'elements'         => [
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'email_from_name',
                'label' => 'Nome do Remetente',
                'rules' => 'required|max:50',
                'value' => 'Coevs',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'email_from_address',
                'label' => 'E-mail do Remetente',
                'rules' => 'required|min:5|max:50',
                'value' => 'coevs@gmail.com',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'mail_username',
                'label' => 'Usuário de E-mail',
                'rules' => 'required',
                'value' => 'test',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'mail_password',
                'label' => 'Senha de E-mail',
                'rules' => 'required',
                'value' => '0000',
                'class' => 'col-md-6',
            ],

            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'mail_host',
                'label' => 'Host de E-mail',
                'rules' => 'required',
                'value' => 'mail.coevs.co',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'integer',
                'key'   => 'mail_port',
                'label' => 'Porta de E-mail',
                'rules' => 'required',
                'value' => '465',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'mail_secure',
                'label' => 'Criptografia',
                'rules' => 'required',
                'value' => [],
                'class' => 'col-md-3',
            ],
        ],
    ],
    'cookie_settings' => [
        'title'    => 'Configurações de Cookies',
        'icon'     => 'cil-bug',
        'elements' => [
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'cookie_title',
                'label' => 'Título dos Cookies',
                'rules' => 'required',
                'value' => 'Cookies Consent',
                'class' => 'col-md-12',
            ],
            [
                'type'  => 'textarea',
                'data'  => 'string',
                'key'   => 'cookie_summary',
                'label' => 'Resumo dos Cookies',
                'rules' => 'required',
                'value' => 'Este site usa cookies para ajudar você a ter uma experiência de navegação superior e mais relevante.',
                'class' => 'col-md-12',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'cookie_url',
                'label' => 'URL da Página de Cookies',
                'rules' => 'required',
                'value' => '/',
                'class' => 'col-md-12',
            ],
            [
                'type'  => 'switch',
                'data'  => 'bool',
                'key'   => 'cookie_status',
                'label' => 'Ativar Cookies',
                'rules' => 'boolean',
                'value' => true,
                'class' => 'col-md-6',
            ],
        ],
    ],
    'hide_settings' => [
        'title'    => 'hide',
        'elements' => [
            [
                'data'  => 'bool',
                'key'   => 'deposit_rewards',
                'rules' => 'boolean',
                'value' => true,
            ],
            [
                'data'  => 'bool',
                'key'   => 'payment_rewards',
                'rules' => 'boolean',
                'value' => true,
            ],
        ],
    ],
];
