<?php

namespace App\Enums;

enum SystemWalletUUID: string
{
    case EXTERNAL_BANKING_NETWORK = 'EXTERNAL_BANKING_NETWORK';
    case EXTERNAL_GATEWAY_NETWORK = 'EXTERNAL_GATEWAY_NETWORK';
    case GATEWAY_STRIPE_HOLDING = 'GATEWAY_STRIPE_HOLDING';
    case GATEWAY_PAYPAL_HOLDING = 'GATEWAY_PAYPAL_HOLDING';
    case GATEWAY_PIX_HOLDING = 'GATEWAY_PIX_HOLDING';
    case GATEWAY_PIX_PAYOUT_HOLDING = 'GATEWAY_PIX_PAYOUT_HOLDING';
    case SYSTEM_REVENUE = 'SYSTEM_REVENUE';
    case SYSTEM_REVENUE_FX = 'SYSTEM_REVENUE_FX';
    case SYSTEM_REFUND = 'SYSTEM_REFUND';
    case SYSTEM_CHARGEBACK = 'SYSTEM_CHARGEBACK';
    case SYSTEM_ADJUSTMENT = 'SYSTEM_ADJUSTMENT';
    case SYSTEM_ADJUSTMENT_LEGACY = 'SYSTEM_ADJUSTMENT_LEGACY';
    case SYSTEM_VOUCHER = 'SYSTEM_VOUCHER';
    case SYSTEM_CASHBACK = 'SYSTEM_CASHBACK';
    case SYSTEM_GENERAL = 'SYSTEM-GENERAL'; // Legacy
}
